# Generated by Django 4.0.5 on 2022-06-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tags', models.CharField(choices=[('Action', 'Action'), ('Horror', 'horror'), ('Thriller', 'Thriller')], max_length=20)),
                ('R_rating', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_series', models.BooleanField(default=True)),
                ('movie_rating', models.CharField(max_length=30, null=True)),
                ('running_time', models.CharField(max_length=30, null=True)),
                ('release_year', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('season_number', models.CharField(max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.film')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('episode_number', models.CharField(max_length=200)),
                ('episode_name', models.CharField(max_length=200, null=True)),
                ('episode_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.season')),
            ],
        ),
    ]
